version: "3.9"
services:
  afp:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "548:548"
    volumes:
      - ./example:/var/afpshare:rw
    environment:
      USERS: |
        [
          { "username": "testuser", "password": "password", "uid": 1000 }
        ]
      SHARES: |
        [
          { "username": "testuser", "path": "/var/afpshare/testuser" }
        ]
